# n.yaml
#
# Crowdin configuration file for XenonHD
#
# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api_key_env: XENONHD_CROWDIN_API_KEY
base_path_env: XENONHD_CROWDIN_BASE_PATH_N
project_identifier: xenonhd-rom
preserve_hierarchy: true

files:
# Frameworks

  # framework-res
  -
    source:      '/frameworks/base/core/res/res/values/xenonhd_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: &anchor
      android_code:
        af: af
        am: am
        ar: ar
        as: as-rIN
        ast: ast-rES
        az: az-rAZ
        be: be-rBY
        bg: bg
        bn: bn-rBD
        bs: bs-rBA
        ca: ca
        cs: cs
        cy: cy
        da: da
        de: de
        el: el
        en-AU: en-rAU
        en-GB: en-rGB
        en-IN: en-rIN
        en-PT: en-rPT
        eo: eo
        es-ES: es
        es-MX: es-rMX
        es-US: es-rUS
        et: et-rEE
        eu: eu-rES
        fa: fa
        fi: fi
        fr: fr
        fr-CA: fr-rCA
        fy-NL: fy-rNL
        gl: gl-rES
        gu-IN: gu-rIN
        he: iw
        hi: hi
        hr: hr
        hu: hu
        hy-AM: hy-rAM
        id: in
        is: is-rIS
        it: it
        ja: ja
        ka: ka-rGE
        kab: kab-rDZ
        kk: kk-rKZ
        km: km-rKH
        kn: kn-rIN
        ko: ko
        ku: ku
        ky: ky-rKG
        lb: lb
        lo: lo-rLA
        lt: lt
        lv: lv
        mk: mk-rMK
        ml-IN: ml-rIN
        mn: mn-rMN
        mr: mr-rIN
        ms: ms-rMY
        my: my-rMM
        nb: nb
        ne-NP: ne-rNP
        nl: nl
        or: or-rIN
        pa-IN: pa-rIN
        pl: pl
        pt-PT: pt-rPT
        pt-BR: pt-rBR
        rm-CH: rm
        ro: ro
        ru: ru
        sc: sc-rIT
        si-LK: si-rLK
        sk: sk
        sl: sl
        sq: sq-rAL
        sr: sr
        sv-SE: sv
        sw: sw
        ta: ta-rIN
        te: te-rIN
        th: th
        tl: tl
        tr: tr
        ug: ug
        uk: uk
        ur-PK: ur-rPK
        uz: uz-rUZ
        vi: vi
        zh-CN: zh-rCN
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        zu: zu

# SystemUI
  -
    source:      '/frameworks/base/packages/SystemUI/res/values/xenonhd_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Packages

  # CMParts
  -
    source:      '/packages/apps/CMParts/res/values/xenonhd_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Settings
  -
    source:      '/packages/apps/Settings/res/values/xenonhd_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # XenonOTA
  -
    source:      '/packages/apps/XenonOTA/app/src/main/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
